export interface Language {
  code: string;
  i18nKey: string;
  nativeName: string; // 若未配置 i18n，将展示 nativeName
  promptName: string; // 用于构建 prompt 的语言名称，使用英语
  searchTerms: string[];
}

export const LANGUAGES: Language[] = [
  {
    code: "en",
    i18nKey: "languages.en",
    nativeName: "English",
    promptName: "English",
    searchTerms: ["英语", "english", "eng", "british", "american"],
  },
  {
    code: "es",
    i18nKey: "languages.es",
    nativeName: "Español",
    promptName: "Spanish",
    searchTerms: ["西班牙语", "spanish", "espanol", "español", "castellano"],
  },
  {
    code: "fr",
    i18nKey: "languages.fr",
    nativeName: "Français",
    promptName: "French",
    searchTerms: ["法语", "french", "francais", "français"],
  },
  {
    code: "pt",
    i18nKey: "languages.pt",
    nativeName: "Português",
    promptName: "Portuguese",
    searchTerms: ["葡萄牙语", "portuguese", "portugues", "português", "luso"],
  },
  {
    code: "it",
    i18nKey: "languages.it",
    nativeName: "Italiano",
    promptName: "Italian",
    searchTerms: ["意大利语", "italian", "italiano"],
  },
  {
    code: "ro",
    i18nKey: "languages.ro",
    nativeName: "Română",
    promptName: "Romanian",
    searchTerms: ["罗马尼亚语", "romanian", "romana", "română", "roumanian"],
  },
  {
    code: "nl",
    i18nKey: "languages.nl",
    nativeName: "Nederlands",
    promptName: "Dutch",
    searchTerms: ["荷兰语", "dutch", "nederlands", "holland"],
  },
  {
    code: "de",
    i18nKey: "languages.de",
    nativeName: "Deutsch",
    promptName: "German",
    searchTerms: ["德语", "german", "deutsch", "alemán", "allemand"],
  },
  {
    code: "ru",
    i18nKey: "languages.ru",
    nativeName: "Русский",
    promptName: "Russian",
    searchTerms: ["俄语", "russian", "russkiy", "русский"],
  },
  {
    code: "uk",
    i18nKey: "languages.uk",
    nativeName: "Українська",
    promptName: "Ukrainian",
    searchTerms: ["乌克兰语", "ukrainian", "ukrainska", "українська"],
  },
  {
    code: "pl",
    i18nKey: "languages.pl",
    nativeName: "Polski",
    promptName: "Polish",
    searchTerms: ["波兰语", "polish", "polski"],
  },
  {
    code: "cs",
    i18nKey: "languages.cs",
    nativeName: "Čeština",
    promptName: "Czech",
    searchTerms: ["捷克语", "czech", "cestina", "čeština"],
  },
  {
    code: "zh-CN",
    i18nKey: "languages.zh-CN",
    nativeName: "简体中文",
    promptName: "Simplified Chinese",
    searchTerms: ["简体中文", "simplified chinese", "mandarin", "putonghua", "zhongwen"],
  },
  {
    code: "zh-TW",
    i18nKey: "languages.zh-TW",
    nativeName: "繁體中文",
    promptName: "Traditional Chinese",
    searchTerms: ["繁體中文", "traditional chinese", "mandarin", "guoyu", "zhongwen"],
  },
  {
    code: "yue",
    i18nKey: "languages.yue",
    nativeName: "廣東話",
    promptName: "Cantonese",
    searchTerms: ["粤语", "cantonese", "guangdonghua", "gwongdungwa", "廣東話"],
  },
  {
    code: "lzh",
    i18nKey: "languages.lzh",
    nativeName: "文言",
    promptName: "Literary Chinese",
    searchTerms: ["文言文", "literary chinese", "classical chinese", "wenyan"],
  },
  {
    code: "ja",
    i18nKey: "languages.ja",
    nativeName: "日本語",
    promptName: "Japanese",
    searchTerms: ["日语", "japanese", "nihongo", "nippongo", "日本語"],
  },
  {
    code: "ko",
    i18nKey: "languages.ko",
    nativeName: "한국어",
    promptName: "Korean",
    searchTerms: ["韩语", "korean", "hanguk-eo", "hangugeo", "한국어"],
  },
  {
    code: "ar",
    i18nKey: "languages.ar",
    nativeName: "العربية الفصحى",
    promptName: "Standard Arabic",
    searchTerms: ["标准阿拉伯语", "standard arabic", "arabic", "fusha", "العربية"],
  },
  {
    code: "ar-EG",
    i18nKey: "languages.ar-EG",
    nativeName: "العربية المصرية",
    promptName: "Egyptian Arabic",
    searchTerms: ["埃及阿拉伯语", "egyptian arabic", "masri", "masry", "مصري"],
  },
  {
    code: "apc",
    i18nKey: "languages.apc",
    nativeName: "شامي",
    promptName: "North Levantine Arabic",
    searchTerms: ["北利万阿拉伯语", "north levantine arabic", "levantine", "shami", "شامي"],
  },
  {
    code: "apd",
    i18nKey: "languages.apd",
    nativeName: "العربية السودانية",
    promptName: "Sudanese Arabic",
    searchTerms: ["苏丹阿拉伯语", "sudanese arabic", "sudani", "سوداني"],
  },
  {
    code: "afb",
    i18nKey: "languages.afb",
    nativeName: "العربية الخليجية",
    promptName: "Gulf Arabic",
    searchTerms: ["海湾阿拉伯语", "gulf arabic", "khaleeji", "خليجي"],
  },
  {
    code: "acm",
    i18nKey: "languages.acm",
    nativeName: "العراقية",
    promptName: "Iraqi Arabic",
    searchTerms: ["伊拉克阿拉伯语", "iraqi arabic", "iraqi", "عراقي"],
  },
  {
    code: "acw",
    i18nKey: "languages.acw",
    nativeName: "الحجازية",
    promptName: "Hejazi Arabic",
    searchTerms: ["希贾兹阿拉伯语", "hejazi arabic", "hejazi", "حجازي"],
  },
  {
    code: "ars",
    i18nKey: "languages.ars",
    nativeName: "النجدية",
    promptName: "Najdi Arabic",
    searchTerms: ["纳吉地阿拉伯语", "najdi arabic", "najdi", "نجدي"],
  },
  {
    code: "ayn",
    i18nKey: "languages.ayn",
    nativeName: "اليمنية",
    promptName: "Yemeni Arabic",
    searchTerms: ["也门阿拉伯语", "yemeni arabic", "yemeni", "يمني"],
  },
  {
    code: "ary",
    i18nKey: "languages.ary",
    nativeName: "الدارجة",
    promptName: "Maghrebi Arabic",
    searchTerms: ["马格里布阿拉伯语", "maghrebi arabic", "darija", "maghrebi", "الدارجة"],
  },
  {
    code: "mey",
    i18nKey: "languages.mey",
    nativeName: "حسانية",
    promptName: "Hassaniya Arabic",
    searchTerms: ["哈萨尼亚阿拉伯语", "hassaniya arabic", "hassaniya", "حسانية"],
  },
  {
    code: "ar-x-classical",
    i18nKey: "languages.ar-x-classical",
    nativeName: "العربية الكلاسيكية",
    promptName: "Classical Arabic",
    searchTerms: ["古典阿拉伯语", "classical arabic", "quranic arabic", "classical"],
  },
  {
    code: "hi",
    i18nKey: "languages.hi",
    nativeName: "हिन्दी",
    promptName: "Hindi",
    searchTerms: ["印地语", "hindi", "hindī", "हिन्दी"],
  },
  {
    code: "sa",
    i18nKey: "languages.sa",
    nativeName: "संस्कृतम्",
    promptName: "Sanskrit",
    searchTerms: ["梵语", "sanskrit", "samskritam", "संस्कृतम्"],
  },
  {
    code: "bn",
    i18nKey: "languages.bn",
    nativeName: "বাংলা",
    promptName: "Bengali",
    searchTerms: ["孟加拉语", "bengali", "bangla", "বাংলা"],
  },
  {
    code: "te",
    i18nKey: "languages.te",
    nativeName: "తెలుగు",
    promptName: "Telugu",
    searchTerms: ["泰卢固语", "telugu", "తెలుగు"],
  },
  {
    code: "mr",
    i18nKey: "languages.mr",
    nativeName: "मराठी",
    promptName: "Marathi",
    searchTerms: ["马拉地语", "marathi", "मराठी"],
  },
  {
    code: "ur",
    i18nKey: "languages.ur",
    nativeName: "اردو",
    promptName: "Urdu",
    searchTerms: ["乌尔都语", "urdu", "اردو"],
  },
  {
    code: "gu",
    i18nKey: "languages.gu",
    nativeName: "ગુજરાતી",
    promptName: "Gujarati",
    searchTerms: ["古吉拉特语", "gujarati", "ગુજરાતી"],
  },
  {
    code: "ta",
    i18nKey: "languages.ta",
    nativeName: "தமிழ்",
    promptName: "Tamil",
    searchTerms: ["泰米尔语", "tamil", "தமிழ்"],
  },
  {
    code: "bho",
    i18nKey: "languages.bho",
    nativeName: "भोजपुरी",
    promptName: "Bhojpuri",
    searchTerms: ["博杰普尔语", "bhojpuri", "भोजपुरी"],
  },
  {
    code: "mai",
    i18nKey: "languages.mai",
    nativeName: "मैथिली",
    promptName: "Maithili",
    searchTerms: ["迈蒂利语", "maithili", "मैथिली"],
  },
  {
    code: "ml",
    i18nKey: "languages.ml",
    nativeName: "മലയാളം",
    promptName: "Malayalam",
    searchTerms: ["马拉雅拉姆语", "malayalam", "മലയാളം"],
  },
  {
    code: "id",
    i18nKey: "languages.id",
    nativeName: "Bahasa Indonesia",
    promptName: "Indonesian",
    searchTerms: ["印度尼西亚语", "indonesian", "bahasa indonesia", "indo"],
  },
  {
    code: "jv",
    i18nKey: "languages.jv",
    nativeName: "Basa Jawa",
    promptName: "Javanese",
    searchTerms: ["爪哇语", "javanese", "basa jawa", "jowo"],
  },
  {
    code: "tl",
    i18nKey: "languages.tl",
    nativeName: "Tagalog",
    promptName: "Tagalog",
    searchTerms: ["他加禄语", "tagalog", "filipino", "wikang tagalog"],
  },
  {
    code: "vi",
    i18nKey: "languages.vi",
    nativeName: "Tiếng Việt",
    promptName: "Vietnamese",
    searchTerms: ["越南语", "vietnamese", "tieng viet", "tiếng việt"],
  },
  {
    code: "th",
    i18nKey: "languages.th",
    nativeName: "ไทย",
    promptName: "Thai",
    searchTerms: ["泰语", "thai", "ภาษาไทย", "ไทย"],
  },
  {
    code: "my",
    i18nKey: "languages.my",
    nativeName: "မြန်မာ",
    promptName: "Burmese",
    searchTerms: ["缅甸语", "burmese", "myanmar", "မြန်မာ"],
  },
  {
    code: "si",
    i18nKey: "languages.si",
    nativeName: "සිංහල",
    promptName: "Sinhalese",
    searchTerms: ["僧伽罗语", "sinhalese", "sinhala", "සිංහල"],
  },
  {
    code: "tr",
    i18nKey: "languages.tr",
    nativeName: "Türkçe",
    promptName: "Turkish",
    searchTerms: ["土耳其语", "turkish", "turkce", "türkçe"],
  },
  {
    code: "fa",
    i18nKey: "languages.fa",
    nativeName: "فارسی",
    promptName: "Iranian Persian",
    searchTerms: ["伊朗波斯语", "iranian persian", "persian", "farsi", "فارسی"],
  },
  {
    code: "prs",
    i18nKey: "languages.prs",
    nativeName: "دری",
    promptName: "Dari",
    searchTerms: ["达里语", "dari", "دری"],
  },
  {
    code: "tg",
    i18nKey: "languages.tg",
    nativeName: "Тоҷикӣ",
    promptName: "Tajik",
    searchTerms: ["塔吉克语", "tajik", "tojiki", "тоҷикӣ"],
  },
  {
    code: "ps",
    i18nKey: "languages.ps",
    nativeName: "پښتو",
    promptName: "Pashto",
    searchTerms: ["普什图语", "pashto", "pushto", "پښتو"],
  },
  {
    code: "am",
    i18nKey: "languages.am",
    nativeName: "አማርኛ",
    promptName: "Amharic",
    searchTerms: ["阿姆哈拉语", "amharic", "አማርኛ"],
  },
  {
    code: "sw",
    i18nKey: "languages.sw",
    nativeName: "Kiswahili",
    promptName: "Swahili",
    searchTerms: ["斯瓦希里语", "swahili", "kiswahili"],
  },
  {
    code: "ha",
    i18nKey: "languages.ha",
    nativeName: "Hausa",
    promptName: "Hausa",
    searchTerms: ["豪萨语", "hausa", "harshen hausa"],
  },
  {
    code: "yo",
    i18nKey: "languages.yo",
    nativeName: "Yorùbá",
    promptName: "Yoruba",
    searchTerms: ["约鲁巴语", "yoruba", "yorùbá"],
  },
  {
    code: "ig",
    i18nKey: "languages.ig",
    nativeName: "Igbo",
    promptName: "Igbo",
    searchTerms: ["伊博语", "igbo", "asusu igbo"],
  },
  {
    code: "so",
    i18nKey: "languages.so",
    nativeName: "Soomaali",
    promptName: "Somali",
    searchTerms: ["索马里语", "somali", "soomaali"],
  },
  {
    code: "om",
    i18nKey: "languages.om",
    nativeName: "Afaan Oromoo",
    promptName: "Oromo",
    searchTerms: ["奥罗莫语", "oromo", "afaan oromoo"],
  },
  {
    code: "ff",
    i18nKey: "languages.ff",
    nativeName: "Fulfulde",
    promptName: "Fula",
    searchTerms: ["富拉语", "fula", "fulani", "fulfulde"],
  },
  {
    code: "cy",
    i18nKey: "languages.cy",
    nativeName: "Cymraeg",
    promptName: "Welsh",
    searchTerms: ["威尔士语", "welsh", "cymraeg"],
  },
  {
    code: "ga",
    i18nKey: "languages.ga",
    nativeName: "Gaeilge",
    promptName: "Irish Gaelic",
    searchTerms: ["爱尔兰盖尔语", "irish gaelic", "gaeilge", "gaelic"],
  },
  {
    code: "gd",
    i18nKey: "languages.gd",
    nativeName: "Gàidhlig",
    promptName: "Scottish Gaelic",
    searchTerms: ["苏格兰盖尔语", "scottish gaelic", "gàidhlig", "gaelic"],
  },
  {
    code: "ms",
    i18nKey: "languages.ms",
    nativeName: "Bahasa Melayu",
    promptName: "Malay",
    searchTerms: ["马来语", "malay", "bahasa melayu", "melayu"],
  },
  {
    code: "fil",
    i18nKey: "languages.fil",
    nativeName: "Filipino",
    promptName: "Filipino",
    searchTerms: ["菲律宾语", "filipino", "pilipino"],
  },
  {
    code: "hmn",
    i18nKey: "languages.hmn",
    nativeName: "Hmoob",
    promptName: "Hmong",
    searchTerms: ["苗族语", "hmong", "hmoob"],
  },
  {
    code: "ht",
    i18nKey: "languages.ht",
    nativeName: "Kreyòl Ayisyen",
    promptName: "Haitian Creole",
    searchTerms: ["海地克里奥尔语", "haitian creole", "kreyol", "kreyòl ayisyen"],
  },
  {
    code: "km",
    i18nKey: "languages.km",
    nativeName: "ខ្មែរ",
    promptName: "Khmer",
    searchTerms: ["高棉语", "khmer", "cambodian", "ខ្មែរ"],
  },
  {
    code: "lb",
    i18nKey: "languages.lb",
    nativeName: "Lëtzebuergesch",
    promptName: "Luxembourgish",
    searchTerms: ["卢森堡语", "luxembourgish", "letzebuergesch", "lëtzebuergesch"],
  },
  {
    code: "lo",
    i18nKey: "languages.lo",
    nativeName: "ລາວ",
    promptName: "Lao",
    searchTerms: ["老挝语", "lao", "laotian", "ລາວ"],
  },
  {
    code: "br",
    i18nKey: "languages.br",
    nativeName: "Brezhoneg",
    promptName: "Breton",
    searchTerms: ["布列塔尼语", "breton", "brezhoneg"],
  },
  {
    code: "sv",
    i18nKey: "languages.sv",
    nativeName: "Svenska",
    promptName: "Swedish",
    searchTerms: ["瑞典语", "swedish", "svenska"],
  },
  {
    code: "da",
    i18nKey: "languages.da",
    nativeName: "Dansk",
    promptName: "Danish",
    searchTerms: ["丹麦语", "danish", "dansk"],
  },
  {
    code: "no",
    i18nKey: "languages.no",
    nativeName: "Norsk",
    promptName: "Norwegian",
    searchTerms: ["挪威语", "norwegian", "norsk", "bokmål", "nynorsk"],
  },
  {
    code: "fi",
    i18nKey: "languages.fi",
    nativeName: "Suomi",
    promptName: "Finnish",
    searchTerms: ["芬兰语", "finnish", "suomi"],
  },
  {
    code: "is",
    i18nKey: "languages.is",
    nativeName: "Íslenska",
    promptName: "Icelandic",
    searchTerms: ["冰岛语", "icelandic", "islenska", "íslenska"],
  },
  {
    code: "fo",
    i18nKey: "languages.fo",
    nativeName: "Føroyskt",
    promptName: "Faroese",
    searchTerms: ["法罗语", "faroese", "føroyskt", "faeroese"],
  },
  {
    code: "hu",
    i18nKey: "languages.hu",
    nativeName: "Magyar",
    promptName: "Hungarian",
    searchTerms: ["匈牙利语", "hungarian", "magyar"],
  },
  {
    code: "el",
    i18nKey: "languages.el",
    nativeName: "Ελληνικά",
    promptName: "Greek",
    searchTerms: ["希腊语", "greek", "ellinika", "ελληνικά"],
  },
  {
    code: "grc",
    i18nKey: "languages.grc",
    nativeName: "Ἑλληνική",
    promptName: "Ancient Greek",
    searchTerms: ["古希腊语", "ancient greek", "classical greek"],
  },
  {
    code: "el-modern",
    i18nKey: "languages.el-modern",
    nativeName: "Νέα Ελληνικά",
    promptName: "Modern Greek",
    searchTerms: ["现代希腊语", "modern greek", "nea ellinika"],
  },
  {
    code: "sq",
    i18nKey: "languages.sq",
    nativeName: "Shqip",
    promptName: "Albanian",
    searchTerms: ["阿尔巴尼亚语", "albanian", "shqip"],
  },
  {
    code: "lt",
    i18nKey: "languages.lt",
    nativeName: "Lietuvių",
    promptName: "Lithuanian",
    searchTerms: ["立陶宛语", "lithuanian", "lietuviu", "lietuvių"],
  },
  {
    code: "lv",
    i18nKey: "languages.lv",
    nativeName: "Latviešu",
    promptName: "Latvian",
    searchTerms: ["拉脱维亚语", "latvian", "latviesu", "latviešu"],
  },
  {
    code: "et",
    i18nKey: "languages.et",
    nativeName: "Eesti",
    promptName: "Estonian",
    searchTerms: ["爱沙尼亚语", "estonian", "eesti"],
  },
  {
    code: "kk",
    i18nKey: "languages.kk",
    nativeName: "Қазақша",
    promptName: "Kazakh",
    searchTerms: ["哈萨克语", "kazakh", "qazaq", "қазақша"],
  },
  {
    code: "mn",
    i18nKey: "languages.mn",
    nativeName: "Монгол",
    promptName: "Mongolian",
    searchTerms: ["蒙古语", "mongolian", "монгол"],
  },
  {
    code: "ug",
    i18nKey: "languages.ug",
    nativeName: "ئۇيغۇرچە",
    promptName: "Uyghur",
    searchTerms: ["维吾尔语", "uyghur", "uighur", "ئۇيغۇرچە"],
  },
  {
    code: "ka",
    i18nKey: "languages.ka",
    nativeName: "ქართული",
    promptName: "Georgian",
    searchTerms: ["格鲁吉亚语", "georgian", "kartuli", "ქართული"],
  },
  {
    code: "hy",
    i18nKey: "languages.hy",
    nativeName: "Հայերեն",
    promptName: "Armenian",
    searchTerms: ["亚美尼亚语", "armenian", "hayeren", "հայերեն"],
  },
  {
    code: "yi",
    i18nKey: "languages.yi",
    nativeName: "ייִדיש",
    promptName: "Yiddish",
    searchTerms: ["意第绪语", "yiddish", "ייִדיש"],
  },
  {
    code: "he",
    i18nKey: "languages.he",
    nativeName: "עברית",
    promptName: "Hebrew",
    searchTerms: ["希伯来语", "hebrew", "ivrit", "עברית"],
  },
  {
    code: "eu",
    i18nKey: "languages.eu",
    nativeName: "Euskara",
    promptName: "Basque",
    searchTerms: ["巴斯克语", "basque", "euskara"],
  },
  {
    code: "ca",
    i18nKey: "languages.ca",
    nativeName: "Català",
    promptName: "Catalan",
    searchTerms: ["加泰罗尼亚语", "catalan", "catala", "català"],
  },
  {
    code: "gl",
    i18nKey: "languages.gl",
    nativeName: "Galego",
    promptName: "Galician",
    searchTerms: ["加利西亚语", "galician", "galego"],
  },
  {
    code: "mt",
    i18nKey: "languages.mt",
    nativeName: "Malti",
    promptName: "Maltese",
    searchTerms: ["马耳他语", "maltese", "malti"],
  },
  {
    code: "la-vulgar",
    i18nKey: "languages.la-vulgar",
    nativeName: "Sermo Vulgaris",
    promptName: "Vulgar Latin",
    searchTerms: ["通俗拉丁语", "vulgar latin", "late latin"],
  },
  {
    code: "pa",
    i18nKey: "languages.pa",
    nativeName: "ਪੰਜਾਬੀ",
    promptName: "Punjabi",
    searchTerms: ["旁遮普语", "punjabi", "panjabi", "ਪੰਜਾਬੀ"],
  },
  {
    code: "ne",
    i18nKey: "languages.ne",
    nativeName: "नेपाली",
    promptName: "Nepali",
    searchTerms: ["尼泊尔语", "nepali", "नेपाली"],
  },
  {
    code: "zu",
    i18nKey: "languages.zu",
    nativeName: "isiZulu",
    promptName: "Zulu",
    searchTerms: ["祖鲁语", "zulu", "isizulu"],
  },
  {
    code: "xh",
    i18nKey: "languages.xh",
    nativeName: "isiXhosa",
    promptName: "Xhosa",
    searchTerms: ["科萨语", "xhosa", "isixhosa"],
  },
  {
    code: "st",
    i18nKey: "languages.st",
    nativeName: "Sesotho",
    promptName: "Sesotho",
    searchTerms: ["塞索托语", "sesotho", "southern sotho"],
  },
  {
    code: "af",
    i18nKey: "languages.af",
    nativeName: "Afrikaans",
    promptName: "Afrikaans",
    searchTerms: ["南非荷兰语", "afrikaans", "afrikaans language"],
  },
  {
    code: "rw",
    i18nKey: "languages.rw",
    nativeName: "Ikinyarwanda",
    promptName: "Kinyarwanda",
    searchTerms: ["卢旺达语", "kinyarwanda", "ikinyarwanda"],
  },
  {
    code: "su",
    i18nKey: "languages.su",
    nativeName: "Basa Sunda",
    promptName: "Sundanese",
    searchTerms: ["巽他语", "sundanese", "basa sunda"],
  },
  {
    code: "mg",
    i18nKey: "languages.mg",
    nativeName: "Malagasy",
    promptName: "Malagasy",
    searchTerms: ["马拉加什语", "malagasy", "teny malagasy"],
  },
  {
    code: "sm",
    i18nKey: "languages.sm",
    nativeName: "Gagana Sāmoa",
    promptName: "Samoan",
    searchTerms: ["萨摩亚语", "samoan", "gagana samoa", "gagana sāmoa"],
  },
  {
    code: "to",
    i18nKey: "languages.to",
    nativeName: "lea faka-Tonga",
    promptName: "Tongan",
    searchTerms: ["汤加语", "tongan", "faka tonga", "lea faka-tonga"],
  },
  {
    code: "ty",
    i18nKey: "languages.ty",
    nativeName: "Reo Tahiti",
    promptName: "Tahitian",
    searchTerms: ["大溪地语", "tahitian", "reo tahiti"],
  },
  {
    code: "haw",
    i18nKey: "languages.haw",
    nativeName: "ʻŌlelo Hawaiʻi",
    promptName: "Hawaiian",
    searchTerms: ["夏威夷语", "hawaiian", "olelo hawaii", "ʻōlelo hawaiʻi"],
  },
  {
    code: "fj",
    i18nKey: "languages.fj",
    nativeName: "Na Vosa Vakaviti",
    promptName: "Fijian",
    searchTerms: ["斐济语", "fijian", "vakaviti", "na vosa vakaviti"],
  },
  {
    code: "qu",
    i18nKey: "languages.qu",
    nativeName: "Runa Simi",
    promptName: "Quechua",
    searchTerms: ["克丘亚语", "quechua", "runa simi"],
  },
  {
    code: "ay",
    i18nKey: "languages.ay",
    nativeName: "Aymar aru",
    promptName: "Aymara",
    searchTerms: ["艾马拉语", "aymara", "aymar aru"],
  },
  {
    code: "gn",
    i18nKey: "languages.gn",
    nativeName: "Avañe'ẽ",
    promptName: "Guarani",
    searchTerms: ["瓜拉尼语", "guarani", "avañe'ẽ", "avane e"],
  },
  {
    code: "io",
    i18nKey: "languages.io",
    nativeName: "Ido",
    promptName: "Ido",
    searchTerms: ["伊多语", "ido"],
  },
  {
    code: "jbo",
    i18nKey: "languages.jbo",
    nativeName: "la .lojban.",
    promptName: "Lojban",
    searchTerms: ["逻辑语", "lojban", "loglan"],
  },
  {
    code: "pi",
    i18nKey: "languages.pi",
    nativeName: "Pāli",
    promptName: "Pali",
    searchTerms: ["巴利语", "pali", "pāli"],
  },
  {
    code: "tok",
    i18nKey: "languages.tok",
    nativeName: "toki pona",
    promptName: "Toki Pona",
    searchTerms: ["托基波纳语", "toki pona", "tokipona"],
  },
  {
    code: "eo",
    i18nKey: "languages.eo",
    nativeName: "Esperanto",
    promptName: "Esperanto",
    searchTerms: ["世界语", "esperanto", "esperanta"],
  },
  {
    code: "sco",
    i18nKey: "languages.sco",
    nativeName: "Scots",
    promptName: "Scots",
    searchTerms: ["苏格兰语", "scots", "braid scots"],
  },
  {
    code: "non",
    i18nKey: "languages.non",
    nativeName: "Norrœnt mál",
    promptName: "Old Norse",
    searchTerms: ["古诺尔斯语", "old norse", "norse", "norrønt"],
  },
  {
    code: "ang",
    i18nKey: "languages.ang",
    nativeName: "Ænglisc",
    promptName: "Old English",
    searchTerms: ["古英语", "old english", "anglo saxon", "ænglisc"],
  },
  {
    code: "en-GB",
    i18nKey: "languages.en-GB",
    nativeName: "British English",
    promptName: "British English",
    searchTerms: ["英式英语", "british english", "uk english", "brenglish"],
  },
  {
    code: "en-AU",
    i18nKey: "languages.en-AU",
    nativeName: "Australian English",
    promptName: "Australian English",
    searchTerms: ["澳大利亚英语", "australian english", "aussie english"],
  },
  {
    code: "en-CA",
    i18nKey: "languages.en-CA",
    nativeName: "Canadian English",
    promptName: "Canadian English",
    searchTerms: ["加拿大英语", "canadian english", "canuck english"],
  },
  {
    code: "en-IN",
    i18nKey: "languages.en-IN",
    nativeName: "Indian English",
    promptName: "Indian English",
    searchTerms: ["印度英语", "indian english", "indlish"],
  },
  {
    code: "lld",
    i18nKey: "languages.lld",
    nativeName: "Ladin",
    promptName: "Ladin",
    searchTerms: ["拉定语", "ladin"],
  },
  {
    code: "enm",
    i18nKey: "languages.enm",
    nativeName: "Middle English",
    promptName: "Middle English",
    searchTerms: ["中古英语", "middle english", "medieval english"],
  },
  {
    code: "fr-CA",
    i18nKey: "languages.fr-CA",
    nativeName: "Français canadien",
    promptName: "Canadian French",
    searchTerms: ["加拿大法语", "canadian french", "quebec french", "québécois"],
  },
  {
    code: "es-MX",
    i18nKey: "languages.es-MX",
    nativeName: "Español mexicano",
    promptName: "Mexican Spanish",
    searchTerms: ["墨西哥西班牙语", "mexican spanish", "español mexicano", "latam spanish"],
  },
  {
    code: "es-RI",
    i18nKey: "languages.es-RI",
    nativeName: "Español rioplatense",
    promptName: "Rioplatense Spanish",
    searchTerms: ["拉普拉塔河西班牙语", "rioplatense spanish", "rioplatense", "argentinian spanish"],
  },
  {
    code: "fro",
    i18nKey: "languages.fro",
    nativeName: "François",
    promptName: "Old French",
    searchTerms: ["古法语", "old french", "ancien français"],
  },
  {
    code: "gmh",
    i18nKey: "languages.gmh",
    nativeName: "Mittelhochdeutsch",
    promptName: "Middle High German",
    searchTerms: ["中古高地德语", "middle high german", "mittelhochdeutsch"],
  },
  {
    code: "gsw",
    i18nKey: "languages.gsw",
    nativeName: "Schwiizerdütsch",
    promptName: "Swiss German",
    searchTerms: ["瑞士德语", "swiss german", "schweizerdeutsch", "schwiizerdütsch"],
  },
  {
    code: "pt-BR",
    i18nKey: "languages.pt-BR",
    nativeName: "Português do Brasil",
    promptName: "Brazilian Portuguese",
    searchTerms: ["巴西葡萄牙语", "brazilian portuguese", "português brasileiro", "ptbr"],
  },
  {
    code: "nv",
    i18nKey: "languages.nv",
    nativeName: "Diné bizaad",
    promptName: "Navajo",
    searchTerms: ["纳瓦霍语", "navajo", "diné bizaad", "dine bizaad"],
  },
  {
    code: "bo",
    i18nKey: "languages.bo",
    nativeName: "བོད་སྐད་",
    promptName: "Tibetan",
    searchTerms: ["藏语", "tibetan", "bod skad", "བོད་སྐད་"],
  },
  {
    code: "tt",
    i18nKey: "languages.tt",
    nativeName: "Татарча",
    promptName: "Tatar",
    searchTerms: ["鞑靼语", "tatar", "татарча"],
  },
  {
    code: "la",
    i18nKey: "languages.la",
    nativeName: "Latina",
    promptName: "Latin",
    searchTerms: ["拉丁语", "latin", "latina", "ecclesiastical latin"],
  },
  {
    code: "sk",
    i18nKey: "languages.sk",
    nativeName: "Slovenčina",
    promptName: "Slovak",
    searchTerms: ["斯洛伐克语", "slovak", "slovencina", "slovenčina"],
  },
  {
    code: "sl",
    i18nKey: "languages.sl",
    nativeName: "Slovenščina",
    promptName: "Slovene",
    searchTerms: ["斯洛文尼亚语", "slovene", "slovenian", "slovenščina"],
  },
  {
    code: "sh",
    i18nKey: "languages.sh",
    nativeName: "Srpskohrvatski",
    promptName: "Serbo Croatian",
    searchTerms: ["塞尔维亚-克罗地亚语", "serbo croatian", "srpskohrvatski", "bcs"],
  },
  {
    code: "bg",
    i18nKey: "languages.bg",
    nativeName: "Български",
    promptName: "Bulgarian",
    searchTerms: ["保加利亚语", "bulgarian", "balgarski", "български"],
  },
  {
    code: "mk",
    i18nKey: "languages.mk",
    nativeName: "Македонски",
    promptName: "Macedonian",
    searchTerms: ["马其顿语", "macedonian", "македонски"],
  },
  {
    code: "oc",
    i18nKey: "languages.oc",
    nativeName: "Occitan",
    promptName: "Occitan",
    searchTerms: ["奥克语", "occitan", "lenga d'oc"],
  },
  {
    code: "sc",
    i18nKey: "languages.sc",
    nativeName: "Sardu",
    promptName: "Sardinian",
    searchTerms: ["萨丁尼亚语", "sardinian", "sardu"],
  },
  {
    code: "uz",
    i18nKey: "languages.uz",
    nativeName: "Oʻzbekcha",
    promptName: "Uzbek",
    searchTerms: ["乌兹别克语", "uzbek", "o'zbek", "oʻzbekcha"],
  },
  {
    code: "ky",
    i18nKey: "languages.ky",
    nativeName: "Кыргызча",
    promptName: "Kyrgyz",
    searchTerms: ["吉尔吉斯语", "kyrgyz", "kirghiz", "кыргызча"],
  },
  {
    code: "kn",
    i18nKey: "languages.kn",
    nativeName: "ಕನ್ನಡ",
    promptName: "Kannada",
    searchTerms: ["卡纳达语", "kannada", "ಕನ್ನಡ"],
  },
  {
    code: "ms-MY",
    i18nKey: "languages.ms-MY",
    nativeName: "Bahasa Malaysia",
    promptName: "Malaysian",
    searchTerms: ["马来西亚语", "malaysian", "bahasa malaysia", "malay malaysia"],
  },
  {
    code: "or",
    i18nKey: "languages.or",
    nativeName: "ଓଡ଼ିଆ",
    promptName: "Oriya",
    searchTerms: ["奥里亚语", "oriya", "odia", "ଓଡ଼ିଆ"],
  },
  {
    code: "kw",
    i18nKey: "languages.kw",
    nativeName: "Kernewek",
    promptName: "Cornish",
    searchTerms: ["康沃尔语", "cornish", "kernewek"],
  },
  {
    code: "co",
    i18nKey: "languages.co",
    nativeName: "Corsu",
    promptName: "Corsican",
    searchTerms: ["科西嘉语", "corsican", "corsu"],
  },
  {
    code: "ga-IE",
    i18nKey: "languages.ga-IE",
    nativeName: "Gaeilge",
    promptName: "Irish",
    searchTerms: ["爱尔兰语", "irish", "gaeilge"],
  },
  {
    code: "as",
    i18nKey: "languages.as",
    nativeName: "অসমীয়া",
    promptName: "Assamese",
    searchTerms: ["阿萨姆语", "assamese", "অসমীয়া"],
  },
  {
    code: "be",
    i18nKey: "languages.be",
    nativeName: "Беларуская",
    promptName: "Belarusian",
    searchTerms: ["白俄罗斯语", "belarusian", "belaruskaya", "беларуская"],
  },
  {
    code: "az",
    i18nKey: "languages.az",
    nativeName: "Azərbaycanca",
    promptName: "Azerbaijani",
    searchTerms: ["阿塞拜疆语", "azerbaijani", "azerbaijani turkic", "azərbaycanca"],
  },
  {
    code: "sd",
    i18nKey: "languages.sd",
    nativeName: "سنڌي",
    promptName: "Sindhi",
    searchTerms: ["信德语", "sindhi", "سنڌي"],
  },
  {
    code: "ks",
    i18nKey: "languages.ks",
    nativeName: "कॉशुर / کٲشُر",
    promptName: "Kashmiri",
    searchTerms: ["克什米尔语", "kashmiri", "koshur", "کٲشُر"],
  },
  {
    code: "ku",
    i18nKey: "languages.ku",
    nativeName: "Kurdî",
    promptName: "Kurdish",
    searchTerms: ["库尔德语", "kurdish", "kurdi", "kurdî"],
  },
  {
    code: "kmr",
    i18nKey: "languages.kmr",
    nativeName: "Kurmancî",
    promptName: "Kurmanji Kurdish",
    searchTerms: ["库尔曼吉库尔德语", "kurmanji kurdish", "kurmanji", "kurmancî"],
  },
  {
    code: "ckb",
    i18nKey: "languages.ckb",
    nativeName: "کوردیی سۆرانی",
    promptName: "Sorani Kurdish",
    searchTerms: ["索拉尼库尔德语", "sorani kurdish", "sorani", "کوردیی سۆرانی"],
  },
  {
    code: "tk",
    i18nKey: "languages.tk",
    nativeName: "Türkmençe",
    promptName: "Turkmen",
    searchTerms: ["土库曼语", "turkmen", "turkmence", "türkmençe"],
  },
  {
    code: "wo",
    i18nKey: "languages.wo",
    nativeName: "Wolof",
    promptName: "Wolof",
    searchTerms: ["沃洛夫语", "wolof"],
  },
  {
    code: "sn",
    i18nKey: "languages.sn",
    nativeName: "chiShona",
    promptName: "Shona",
    searchTerms: ["绍纳语", "shona", "chishona"],
  },
  {
    code: "mo",
    i18nKey: "languages.mo",
    nativeName: "Moldovenească",
    promptName: "Moldovan",
    searchTerms: ["摩尔多瓦语", "moldovan", "moldoveneasca", "moldovenească"],
  },
  {
    code: "mi",
    i18nKey: "languages.mi",
    nativeName: "Te Reo Māori",
    promptName: "Maori",
    searchTerms: ["毛利语", "maori", "te reo maori", "te reo māori"],
  },
  {
    code: "gv",
    i18nKey: "languages.gv",
    nativeName: "Gaelg",
    promptName: "Manx",
    searchTerms: ["马恩岛语", "manx", "gaelg"],
  },
  {
    code: "x-braille",
    i18nKey: "languages.x-braille",
    nativeName: "Braille",
    promptName: "Braille",
    searchTerms: ["盲文", "braille", "braille code"],
  },
  {
    code: "la-classical",
    i18nKey: "languages.la-classical",
    nativeName: "Latina Classica",
    promptName: "Classical Latin",
    searchTerms: ["古典拉丁语", "classical latin", "roman latin"],
  },
  {
    code: "x-shakespearean",
    i18nKey: "languages.x-shakespearean",
    nativeName: "Shakespearean English",
    promptName: "Shakespearean",
    searchTerms: ["莎士比亚式英语", "shakespearean", "elizabethean english", "thee thou"],
  },
  {
    code: "lg",
    i18nKey: "languages.lg",
    nativeName: "Luganda",
    promptName: "Luganda",
    searchTerms: ["卢干达语", "luganda", "ganda"],
  },
  {
    code: "hr",
    i18nKey: "languages.hr",
    nativeName: "Hrvatski",
    promptName: "Croatian",
    searchTerms: ["克罗地亚语", "croatian", "hrvatski"],
  },
  {
    code: "sr",
    i18nKey: "languages.sr",
    nativeName: "Српски",
    promptName: "Serbian",
    searchTerms: ["塞尔维亚语", "serbian", "srpski", "српски"],
  },
  {
    code: "sr-Latn",
    i18nKey: "languages.sr-Latn",
    nativeName: "Srpski",
    promptName: "Serbian Latin",
    searchTerms: ["塞尔维亚拉丁语", "serbian latin", "latin serbian", "srpski latinica"],
  },
  {
    code: "bs",
    i18nKey: "languages.bs",
    nativeName: "Bosanski",
    promptName: "Bosnian",
    searchTerms: ["波斯尼亚语", "bosnian", "bosanski"],
  },
  {
    code: "x-klingon",
    i18nKey: "languages.x-klingon",
    nativeName: "tlhIngan Hol",
    promptName: "Klingon",
    searchTerms: ["克林贡语", "klingon", "tlhingan hol"],
  },
  {
    code: "x-dothraki",
    i18nKey: "languages.x-dothraki",
    nativeName: "Dothraki",
    promptName: "Dothraki",
    searchTerms: ["多斯拉克语", "dothraki"],
  },
  {
    code: "x-slang",
    i18nKey: "languages.x-slang",
    nativeName: "Slang",
    promptName: "Slang",
    searchTerms: ["俚语", "slang", "colloquial", "street talk"],
  },
  {
    code: "x-ipa",
    i18nKey: "languages.x-ipa",
    nativeName: "IPA",
    promptName: "International Phonetic Alphabet",
    searchTerms: ["国际音标", "international phonetic alphabet", "ipa", "phonetic"],
  },
  {
    code: "x-base64",
    i18nKey: "languages.x-base64",
    nativeName: "Base64",
    promptName: "Base64",
    searchTerms: ["Base64", "base64", "b64", "encode64"],
  },
  {
    code: "x-emoji",
    i18nKey: "languages.x-emoji",
    nativeName: "Emoji",
    promptName: "Emoji",
    searchTerms: ["表情符号", "emoji", "emojis", "emoticon"],
  },
  {
    code: "x-morse",
    i18nKey: "languages.x-morse",
    nativeName: "Morse Code",
    promptName: "Morse Code",
    searchTerms: ["摩尔斯电码", "morse code", "morse", "cw"],
  },
  {
    code: "x-yoda",
    i18nKey: "languages.x-yoda",
    nativeName: "Yoda",
    promptName: "Yoda",
    searchTerms: ["尤达语", "yoda", "star wars yoda", "yodish"],
  },
  {
    code: "x-binary",
    i18nKey: "languages.x-binary",
    nativeName: "Binary",
    promptName: "Binary",
    searchTerms: ["二进制", "binary", "bits", "0101"],
  },
];