import {
    Dialog,
    DialogTrigger,
    DialogContent,
    DialogTitle,
    DialogDescription,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { ChevronDown, ChevronUp, SearchIcon, Pin, PinOff } from 'lucide-react';
import { useEffect, useMemo, useState } from "react";
import { OpenAI } from '@lobehub/icons';
import { useProviders } from "@/hooks/useProviders";
import { usePinnedModels } from "@/stores/pinned.models.store";
import { usePreferences } from "@/stores/preferences.store";
import { useTranslation } from "react-i18next";

export default function ModelSelectorDialog() {
    const { t } = useTranslation();
    const [open, setOpen] = useState(false);
    const [keyword, setKeyword] = useState("");
    const { selectedModel, setSelectedModel } = usePreferences();

    const { providers } = useProviders();
    // providers -> groups
    const groups = useMemo(() => {
        if (!providers) return [];
        return providers
            .map((p) => {
                const models = (p.models ?? "")
                    .split(",")
                    .map((s) => s.trim())
                    .filter(Boolean);

                return { provider: p, models };
            })
            .filter((g) => g.models.length > 0);
    }, [providers]);

    const { pinned, isPinned, toggle, removeMany } = usePinnedModels();
    // All valid keys that can be generated by the current Dexie data.
    const validKeySet = useMemo(() => {
        const set = new Set<string>();
        for (const g of groups) {
            const pid = g.provider.id;
            if (pid == null) continue;
            for (const m of g.models) set.add(`${pid}:${m}`)
        }
        return set;
    }, [groups])

    // When Dexie data changes: automatically remove pinned items that no longer exist
    useEffect(() => {
        // If providers haven't loaded yet, do not clean up
        if (providers === undefined) return;
        if (!pinned.length) return;

        const invalid = pinned.filter((k) => !validKeySet.has(k));

        if (invalid.length) removeMany(invalid);
    }, [providers, pinned, validKeySet, removeMany]);

    // Calculate pinned items
    const pinnedItems = useMemo(() => {
        // Map for reverse lookup from key to display content
        const map = new Map<string, { providerId: number; providerName: string; model: string }>();

        for (const g of groups) {
            const pid = g.provider.id;
            if (pid == null) continue;
            for (const model of g.models) {
                const key = `${pid}:${model}`;
                map.set(key, { providerId: pid, providerName: g.provider.name, model })
            }
        }

        return pinned
            .map((k) => map.get(k))
            .filter(Boolean) as Array<{ providerId: number; providerName: string; model: string }>;
    }, [groups, pinned])

    // Search Filter Top List
    const filteredPinnedItems = useMemo(() => {
        const q = keyword.trim().toLowerCase();
        if (!q) return pinnedItems;

        return pinnedItems.filter((item) => {
            return (
                item.model.toLowerCase().includes(q) ||
                item.providerName.toLowerCase().includes(q)
            );
        });
    }, [pinnedItems, keyword]);

    // For displaying the "original group area": hide the pinned models.
    const visibleGroups = useMemo(() => {
        return groups
            .map((g) => {
                const pid = g.provider.id;
                if (pid == null) return g;

                const models = g.models.filter((model) => {
                    const key = `${pid}:${model}`;
                    return !pinned.includes(key);
                });

                return { ...g, models };
            })
            .filter((g) => g.models.length > 0);
    }, [groups, pinned])

    // Search Filter for Original Group Area
    const filteredGroups = useMemo(() => {
        const q = keyword.trim().toLowerCase();
        if (!q) return visibleGroups;

        return visibleGroups
            .map((g) => {
                const models = g.models.filter((model) => {
                    return (
                        model.toLowerCase().includes(q) ||
                        g.provider.name.toLowerCase().includes(q)
                    );
                });

                return { ...g, models };
            })
            .filter((g) => g.models.length > 0);
    }, [visibleGroups, keyword]);

    const selectedModelLabel = useMemo(() => {
        if (!selectedModel) return t("common.preferences.select_model.dialog_trigger");

        const provider = providers?.find((p) => p.id === selectedModel.providerId);
        if (!provider) return selectedModel.model;

        return `${selectedModel.model} | ${provider.name}`;
    }, [selectedModel, providers])

    const renderModelItem = ({
        providerId,
        providerName,
        model,
    }: {
        providerId: number;
        providerName: string;
        model: string;
    }) => {
        const key = `${providerId}:${model}`;
        const selectedNow =
            selectedModel?.providerId === providerId &&
            selectedModel?.model === model;

        const pinnedNow = isPinned(key);
        const Icon = pinnedNow ? PinOff : Pin;

        return (
            <div
                key={key}
                onClick={() => {
                    setSelectedModel({
                        providerId,
                        model,
                    });
                    setOpen(false);
                }}
                className={cn(
                    "relative flex flex-row justify-between items-center rounded-md text-sm",
                    "hover:bg-[#ececec] hover:cursor-pointer dark:hover:bg-[#353535]",
                    selectedNow &&
                    "bg-[#ececec] dark:bg-[#353535] before:content-[''] before:absolute before:left-0 before:top-1 before:bottom-1 before:w-0.75 before:rounded-full before:bg-gray-300"
                )}
            >
                <div className="pl-1 flex flex-row items-center gap-2 mx-2 py-2 min-w-0">
                    <OpenAI className="w-4 h-4 shrink-0" />
                    <span className="truncate">{model}</span>
                    <span className="text-muted-foreground truncate">{providerName}</span>
                </div>

                <div className="flex items-center justify-center mr-2 shrink-0">
                    <Icon
                        className="w-4 h-4 hover:cursor-pointer text-muted-foreground hover:text-foreground"
                        onClick={(e) => {
                            e.stopPropagation();
                            toggle(key);
                        }}
                    />
                </div>
            </div>
        );
    };

    return (

        <>
            <Dialog open={open} onOpenChange={setOpen}>
                <DialogTrigger>
                    <button
                        className={cn(
                            "text-sm flex items-center gap-3 border px-3 py-1 w-fit rounded-lg hover:cursor-pointer hover:bg-[#ececec] dark:bg-[#2f2f2f] dark:hover:bg-[#424242] text-muted-foreground border-none",
                            "max-w-80 min-w-0",
                            open && "bg-[#ececec] dark:bg-[#424242]"
                        )}
                    >
                        <span className="flex-1 min-w-0 truncate text-left">
                            {selectedModelLabel}
                        </span>
                        {open ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                    </button>
                </DialogTrigger>

                <DialogContent
                    showCloseButton={false}
                    className="w-[90vw] h-[80vh] sm:max-w-120 sm:max-h-140 p-0 dark:bg-[#212121]"
                >
                    <DialogTitle className="sr-only">{t("common.preferences.select_model.dialog_title")}</DialogTitle>
                    <DialogDescription className="sr-only">{t("common.preferences.select_model.dialog_description")}</DialogDescription>

                    <div className="flex flex-col py-2 min-h-0 overflow-hidden">
                        <div className="border-b px-4 pt-2 pb-3 flex flex-row items-center gap-2">
                            <SearchIcon className="w-5 h-5 text-muted-foreground" />
                            <input
                                placeholder={t("common.preferences.select_model.search")}
                                className="flex-1 border-0 outline-none text-sm"
                                value={keyword}
                                onChange={(e) => setKeyword(e.target.value)}
                            />
                        </div>

                        <div className="flex-1 px-2 py-2 pr-3 overflow-y-auto flex flex-col gap-4">
                            {filteredPinnedItems.length > 0 && (
                                <div className="flex flex-col gap-2">
                                    <div className="text-muted-foreground px-1 text-xs">
                                        {t("common.preferences.select_model.pinned")}
                                    </div>

                                    <div className="flex flex-col gap-2">
                                        {filteredPinnedItems.map((item) =>
                                            renderModelItem({
                                                providerId: item.providerId,
                                                providerName: item.providerName,
                                                model: item.model,
                                            })
                                        )}
                                    </div>
                                </div>
                            )}

                            {filteredGroups.map(({ provider, models }) => (
                                <div
                                    key={provider.id}
                                    className="flex flex-col gap-2"
                                >
                                    <div className="text-muted-foreground px-1 text-xs max-w-50 truncate">
                                        {provider.name}
                                    </div>

                                    <div className="flex flex-col gap-2">
                                        {models.map((model) => {
                                            const pid = provider.id;
                                            if (pid == null) return null;

                                            return renderModelItem({
                                                providerId: pid,
                                                providerName: provider.name,
                                                model,
                                            });
                                        })}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </DialogContent>
            </Dialog>
        </>
    )
}